version: '3'

networks:
  neon-system:

services:
  neon-dashboard-container:
    container_name: neon-dashboard-container
    image: nginx:alpine
    networks:
      neon-system:
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - ./dist:/var/www:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/app/config/config.yaml:/var/www/app/config/config.yaml
  neon-server-container:
    container_name: neon-server-container
    image: com.ncc.neon/server:latest
    expose:
      - 8090
    ports:
      - 8090:8090
    environment:
      STATE_DIRECTORY: /states
      SERVER_PORT: 8090
    networks:
      neon-system:
    volumes:
      - ./states:/states
  neon-elasticsearch-container:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
    container_name: neon-elasticsearch-container
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9200
    ports:
      - 9200:9200
    networks:
      neon-system:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 1s
      timeout: 1s
      retries: 30

