version: '3'

networks:
  neon-system:

services:
  neon-dashboard-container:
    container_name: neon-dashboard-container
    image: nginx:alpine
    networks:
      neon-system:
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - ./dist:/var/www:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/app/config/config.yaml:/var/www/app/config/config.yaml
  neon-server-container:
    container_name: neon-server-container
    image: com.ncc.neon/server:latest
    expose:
      - 8090
    ports:
      - 8090:8090
    environment:
      STATE_DIRECTORY: /states
      SERVER_PORT: 8090
    networks:
      neon-system:
    volumes:
      - ./states:/states

