version: '3'

networks:
  neon-net:

services:
  neon-dash:
    container_name: neon-dash
    image: nginx:alpine
    ports: 
      - 4199:80
    networks:
      neon-net:
    volumes:
      - ${NEON_DASH_DIST:-../../dist}:/var/www:ro
      - ./resources/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./resources/config.yaml:/var/www/app/config/config.yaml
  neon-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: neon-es
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false      
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9199:9200
    expose:
      - 9200      
    networks:
      neon-net:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 1s
      timeout: 1s
      retries: 30
  neon-server:
    environment:
      STATE_DIRECTORY: /config
      SERVER_PORT: 80
    volumes:
      - ./resources:/config
    image: com.ncc.neon/server:latest
    container_name: neon-server
    expose:
      - 80
    networks:
      neon-net:
  neon-data-load:
    volumes:
      - ./data:/data
    image: node:12.4.0-slim
    depends_on:
      - neon-es
    entrypoint: []
    command: /bin/bash /data/load.sh
    container_name: neon-data-load
    networks:
      neon-net:
  