datastores:
    es1:
        host: localhost
        type: elasticsearchrest
        databases:
            ariel_simpost:
                prettyName: ARIEL VODNO 2018
                tables:
                    ui_output:
                        prettyName: UI Output
                        fields:
                            - columnName: createdAt
                              prettyName: Date Created
                            - columnName: location
                              prettyName: Location
                            - columnName: need
                              prettyName: Need
                            - columnName: originalText
                              prettyName: Original Text
                            - columnName: translatedText
                              prettyName: Translated Text
                            - columnName: cluster
                              prettyName: Cluster ID
                        mappings:
                          date: createdAt
            apan:
                prettyName: ELISA APAN
                tables:
                    ui_output:
                        prettyName: UI Output
                        fields:
                            - columnName: createdAt
                              prettyName: Date Created
                            - columnName: threadName
                              prettyName: Thread Title
                            - columnName: originalText
                              prettyName: Original Text
                            - columnName: author
                              prettyName: Author
                        mappings:
                          date: createdAt
dashboards:
    category: 'Select a task...'
    choices:
        vodno:
            name: 'SIMPOST'
            category: 'Select a datastore...'
            choices:
                ariel_simpost:
                    name: ARIEL VODNO 2018
                    layout: ariel_simpost
                    tables:
                        table_key_1: es1.ariel_simpost.ui_output
                    fields:
                        original_text_key: es1.ariel_simpost.ui_output.originalText
                        translated_text_key: es1.ariel_simpost.ui_output.translatedText
                        date_field_key: es1.ariel_simpost.ui_output.createdAt
                        id_field_key: es1.ariel_simpost.ui_output._id
                        group_field_key: es1.ariel_simpost.ui_output.need
                        cluster_field_key: es1.ariel_simpost.ui_output.cluster
                        cluster_name_field_key: es1.ariel_simpost.ui_output.clusterName
                        latitude_key: es1.ariel_simpost.ui_output.geoLocation.lat
                        longitude_key: es1.ariel_simpost.ui_output.geoLocation.lon
                        text_cloud_data_key: es1.ariel_simpost.ui_output.location
                    options:
                        connectOnLoad: false
                        simpleFilter:
                            tableKey: table_key_1
                            fieldKey: original_text_key
                            placeHolder: Search
                    contributors:
                        mit-ll:
                            orgName: 'Massachusettes Institute of Technology Lincoln Laboratory'
                            abbreviation: 'MIT/LL'
                            contactName: 'Doug Jones'
                            contactEmail: 'daj@ll.mit.edu'
                            website: 'https://www.ll.mit.edu/'
                            logo: 'mit-lincoln-laboratory.jpg'
                        cmu:
                            orgName: 'Carnegie Mellon University'
                            abbreviation: 'CMU'
                            contactName: 'Alan W Black'
                            contactEmail: 'awb@cs.cmu.edu'
                            website: 'https://www.cs.cmu.edu/'
                            logo: 'CMU-logo.jpg'
        apan:
            name: 'APAN'
            category: 'Select a datastore...'
            choices:
                apan:
                    name: ELISA APAN
                    layout: elisa_apan
                    tables:
                        table_key_1: es1.apan.ui_output
                    fields:
                        original_text_key: es1.apan.ui_output.originalText
                        author_field_key: es1.apan.ui_output.author
                        date_field_key: es1.apan.ui_output.createdAt
                        id_field_key: es1.apan.ui_output._id
                        thread_name_field_key: es1.apan.ui_output.threadName
                        latitude_key: es1.apan.ui_output.geoLocations.lat
                        longitude_key: es1.apan.ui_output.geoLocations.lon
                        topics_field_key: es1.apan.ui_output.topics
                        text_cloud_data_key_LOC: es1.apan.ui_output.LOC
                        text_cloud_data_key_PER: es1.apan.ui_output.PER
                        text_cloud_data_key_GPE: es1.apan.ui_output.GPE
                        text_cloud_data_key_ORG: es1.apan.ui_output.ORG
                    options:
                        connectOnLoad: true
                        simpleFilter:
                            tableKey: table_key_1
                            fieldKey: original_text_key
                            placeHolder: Search
                    contributors:
                        apan:
                            orgName: 'All Partners Access Network'
                            abbreviation: 'APAN'
                            contactName: 'Mariel Cooley'
                            contactEmail: 'mariel.cooley@mpe.apan.org'
                            website: 'https://www.apan.org/'
                            logo: 'apan-logo.png'
                        rpi:
                            orgName: 'Rensselaer Polytechnic Institute'
                            abbreviation: 'RPI'
                            contactName: 'Heng Ji'
                            contactEmail: 'jih@rpi.edu'
                            website: 'http://nlp.cs.rpi.edu/'
                            logo: 'RPI-logo.png'
                        isi:
                            orgName: 'University of Southern California, Information Sciences Institute'
                            abbreviation: 'USC/ISI'
                            contactName: 'Jonathan May'
                            contactEmail: 'jonmay@isi.edu'
                            website: 'https://www.isi.edu/'
                            logo: 'ISI-logo.png'

layouts:
    ariel_simpost:
        - name: Data Table
          type: dataTable
          icon: ViewData64
          col: 1
          row: 1
          sizex: 4
          sizey: 10
          bindings:
            title: Tweets
            tableKey: table_key_1
            idField: id_field_key
            sortField: date_field_key
            limit: 100
            showFields:
                - date_field_key
                - original_text_key
                - group_field_key
            customColumnWidths:
                - - date_field_key
                  - 25
                - - original_text_key
                  - 300
                - - group_field_key
                  - 15
            filterable: false
            singleFilter: true
            ignoreSelf: false
        - name: Map
          type: map
          icon: Map64
          col: 5
          row: 1
          sizex: 5
          sizey: 10
          bindings:
              title: Locations
              tableKey: table_key_1
              filterable: true
              name: EVENTS
              show: true
              type: cluster
              limit: 5000
              layers:
                  - title: Map
                    tableKey: table_key_1
                    latitudeField: latitude_key
                    longitudeField: longitude_key
                    dateField: date_field_key
                    colorField: group_field_key
              mapType: leaflet
              west: 21.3
              north: 42.2
              east: 21.6
              south: 41.8
        - name: Text Cloud
          type: textCloud
          icon: TagCloud64
          col: 5
          row: 11
          sizex: 5
          sizey: 4
          selected: true
          bindings:
              title: Locations
              tableKey: table_key_1
              dataField: text_cloud_data_key
              preFilter: false
        - name: Bar Chart
          type: aggregation
          icon: bar_chart
          col: 10
          row: 1
          sizex: 3
          sizey: 9
          bindings:
              title: Needs
              type: bar-h
              tableKey: table_key_1
              xField: group_field_key
              limit: 10
              groupField: group_field_key
              sortByAggregation: false
        - name: Annotation Viewer
          type: annotationViewer
          icon: documentViewer64
          col: 1
          row: 11
          sizex: 2
          sizey: 4
          bindings:
              title: Original Text
              tableKey: table_key_1
              linkField: original_text_key
              idField: id_field_key
              respondMode: true
        - name: Annotation Viewer
          type: annotationViewer
          icon: documentViewer64
          col: 3
          row: 11
          sizex: 2
          sizey: 4
          bindings:
              title: Translated Text
              tableKey: table_key_1
              linkField: translated_text_key
              idField: id_field_key
              respondMode: true
    elisa_apan:
        - name: Data Table
          type: dataTable
          icon: ViewData64
          col: 1
          row: 1
          sizex: 3
          sizey: 9
          bindings:
            title: Posts
            tableKey: table_key_1
            idField: thread_name_field_key
            sortField: date_field_key
            limit: 100
            showFields:
                - date_field_key
                - original_text_key
                - thread_name_field_key
            customColumnWidths:
                - - date_field_key
                  - 60
                - - original_text_key
                  - 200
                - - thread_name_field_key
                  - 40
            filterable: false
            singleFilter: true
            ignoreSelf: false
            contributionKeys:
                - apan
                - isi
        - name: Annotation Viewer
          type: annotationViewer
          icon: documentViewer64
          col: 1
          row: 11
          sizex: 3
          sizey: 5
          bindings:
              title: Thread Posts
              tableKey: table_key_1
              linkField: original_text_key
              idField: thread_name_field_key
              respondMode: true
              contributionKeys:
                - apan
                - isi
        - name: Map
          type: map
          icon: Map64
          col: 4
          row: 1
          sizex: 6
          sizey: 14
          bindings:
              title: Locations
              tableKey: table_key_1
              filterable: true
              name: EVENTS
              show: true
              type: cluster
              limit: 5000
              layers:
                  - title: Map
                    tableKey: table_key_1
                    latitudeField: latitude_key
                    longitudeField: longitude_key
                    dateField: date_field_key
                    colorField: text_cloud_data_key_LOC
              mapType: leaflet
              west: -75.3
              north: 21.9
              east: -69.6
              south: 15.8
              contributionKeys:
                - apan
                - rpi
        - name: Bar Chart
          type: aggregation
          icon: bar_chart
          col: 10
          row: 1
          sizex: 3
          sizey: 6
          bindings:
              title: Topics
              type: bar-h
              tableKey: table_key_1
              xField: topics_field_key
              limit: 10
              groupField: topics_field_key
              sortByAggregation: false
              contributionKeys:
                - apan
                - isi
        - name: Text Cloud
          type: textCloud
          icon: TagCloud64
          col: 10
          row: 7
          sizex: 3
          sizey: 4
          selected: true
          bindings:
              title: Organizations
              tableKey: table_key_1
              dataField: text_cloud_data_key_ORG
              preFilter: false
              contributionKeys:
                - apan
                - rpi
        - name: Text Cloud
          type: textCloud
          icon: TagCloud64
          col: 10
          row: 7
          sizex: 3
          sizey: 4
          selected: true
          bindings:
              title: Locations
              tableKey: table_key_1
              dataField: text_cloud_data_key_LOC
              preFilter: false
              contributionKeys:
                - apan
                - rpi
