projectIcon: 'assets/images/verdi-favicon.ico'
datastores:
    es1:
        host: localhost
        type: elasticsearchrest
        databases:
            aida-docs-parents:
                prettyName: TA1 Parent Documents
                tables:
                    parents:
                        prettyName: Root Index
                        fields:
                        labelOptions:
            aida-docs-parent-children:
                prettyName: TA1 Child Documents
                tables:
                    parent-children:
                         prettyName: Child Index
                         fields:
                         labelOptions:
            gaia-graph:
                prettyName: GAIA TA1 Graph
                tables:
                    graph:
                        prettyName: Graph Index
                        fields:
                        labelOptions:
            ldc-graph:
                prettyName: LDC TA1 Graph
                tables:
                    graph:
                        prettyName: Graph Index
                        fields:
                        labelOptions:
dashboards:
    category: 'Select...'
    choices:
        gaia-pilot:
            name: GAIA Pilot
            category: 'Select...'
            choices:
                gaia-ta1:
                    name: TA1
                    category: 'Select...'
                    choices:
                        pilot:
                            name: Pilot
                            layout: gaia-ta1-pilot
                            tables:
                                document_table: es1.aida-docs-parents.parents
                                graph_table: es1.gaia-graph.graph
                            fields:
                                document_field_id: es1.aida-docs-parents.parents.id
                                document_field_link: es1.aida-docs-parents.parents.reconstructed

                                graph_field_type: es1.gaia-graph.graph.types
                                graph_field_category: es1.gaia-graph.graph.categories
                            relations:
                                - - es1.aida-docs-parents.parents.id
                                  - es1.gaia-graph.graph.parentIds
                            options:
                                connectOnLoad: true
                                colorMaps:
                                    gaia-graph:
                                        graph:
                                            categories:
                                                ENTITY: '#ADD8E6'
                                                EVENT: '#D98C8C'
                                                RELATION: '#FFE4B5'
        ldc-pilot:
            name: LDC Pilot
            category: 'Select...'
            choices:
                ldc-ta1:
                    name: TA1
                    category: 'Select...'
                    choices:
                        pilot:
                            name: Pilot
                            layout: ldc-ta1-pilot
                            tables:
                                document_table: es1.aida-docs-parents.parents
                                graph_table: es1.ldc-graph.graph
                            fields:
                                document_field_id: es1.aida-docs-parents.parents.id
                                document_field_documenttype: es1.aida-docs-parents.parents.dtype
                                document_field_link: es1.aida-docs-parents.parents.reconstructed

                                graph_field_type: es1.ldc-graph.graph.types
                                graph_field_category: es1.ldc-graph.graph.categories
                            relations:
                                - - es1.aida-docs-parents.parents.id
                                  - es1.ldc-graph.graph.parentIds
                            options:
                                connectOnLoad: false
                                colorMaps:
                                    ldc-graph:
                                        graph:
                                            categories:
                                                ENTITY: '#ADD8E6'
                                                EVENT: '#D98C8C'
                                                RELATION: '#FFE4B5'
layouts:
    gaia-ta1-pilot:
        - type: dataTable
          row: 1
          col: 1
          sizex: 2
          sizey: 17.5
          bindings:
              title: Documents
              tableKey: document_table
              idField: document_field_id
              sortField: document_field_id
              filterable: true
              ignoreSelf: true
              singleFilter: true
              filterFields:
                - document_field_id
              exceptionsToStatus:
                - document_field_id
              allColumnStatus: hide

        - type: aggregation
          row: 1
          col: 3
          sizex: 4
          sizey: 6
          bindings:
              title: Entities
              tableKey: graph_table
              type: bar-h
              xField: graph_field_type
              groupField: graph_field_category
              aggregation: count
              logScaleX: true
              sortByAggregation: true
              unsharedFilterField: graph_field_category
              unsharedFilterValue: ENTITY

        - type: aggregation
          row: 7
          col: 3
          sizex: 4
          sizey: 5.5
          bindings:
              title: Events
              tableKey: graph_table
              type: bar-h
              xField: graph_field_type
              groupField: graph_field_category
              aggregation: count
              logScaleX: true
              sortByAggregation: true
              unsharedFilterField: graph_field_category
              unsharedFilterValue: EVENT

        - type: aggregation
          row: 13
          col: 3
          sizex: 4
          sizey: 6
          bindings:
              title: Relations
              tableKey: graph_table
              type: bar-h
              xField: graph_field_type
              groupField: graph_field_category
              aggregation: count
              logScaleX: true
              sortByAggregation: true
              unsharedFilterField: graph_field_category
              unsharedFilterValue: RELATION

        - type: mediaViewer
          row: 1
          col: 7
          sizex: 6
          sizey: 17.5
          bindings:
              title: 'Media Viewer'
              tableKey: document_table
              idField: document_field_id
              linkField: document_field_link
              linkPrefix: '../Reconstructed/html/gaia/'
              typeField: document_field_documenttype
              clearMedia: false
    ldc-ta1-pilot:
        - type: dataTable
          row: 1
          col: 1
          sizex: 2
          sizey: 17.5
          bindings:
              title: Documents
              tableKey: document_table
              idField: document_field_id
              sortField: document_field_id
              filterable: true
              ignoreSelf: true
              singleFilter: true
              filterFields:
                - document_field_id
              exceptionsToStatus:
                - document_field_id
              allColumnStatus: hide

        - type: aggregation
          row: 1
          col: 3
          sizex: 4
          sizey: 6
          bindings:
              title: Entities
              tableKey: graph_table
              type: bar-h
              xField: graph_field_type
              groupField: graph_field_category
              aggregation: count
              logScaleX: true
              sortByAggregation: true
              unsharedFilterField: graph_field_category
              unsharedFilterValue: ENTITY

        - type: aggregation
          row: 7
          col: 3
          sizex: 4
          sizey: 5.5
          bindings:
              title: Events
              tableKey: graph_table
              type: bar-h
              xField: graph_field_type
              groupField: graph_field_category
              aggregation: count
              logScaleX: true
              sortByAggregation: true
              unsharedFilterField: graph_field_category
              unsharedFilterValue: EVENT

        - type: aggregation
          row: 13
          col: 3
          sizex: 4
          sizey: 6
          bindings:
              title: Relations
              tableKey: graph_table
              type: bar-h
              xField: graph_field_type
              groupField: graph_field_category
              aggregation: count
              logScaleX: true
              sortByAggregation: true
              unsharedFilterField: graph_field_category
              unsharedFilterValue: RELATION

        - type: mediaViewer
          row: 1
          col: 7
          sizex: 6
          sizey: 17.5
          bindings:
              title: 'Media Viewer'
              tableKey: document_table
              idField: document_field_id
              linkField: document_field_link
              linkPrefix: '../Reconstructed/html/ldc/'
              typeField: document_field_documenttype
              clearMedia: false
