datastores:
    es1:
        host: localhost
        type: elasticsearchrest
        databases:
            lorelei_event:
                prettyName: Lorelei Event
                tables:
                    lorelei_event:
                        prettyName: LORELEI Event
                        fields:
                            - columnName: createdAt
                              prettyName: Date Created
                            - columnName: id
                              prettyName: ID
                            - columnName: geoLocations.latitude
                              prettyName: Latitude
                            - columnName: geoLocations.longitude
                              prettyName: Longitude
                            - columnName: originaltext
                              prettyName: Original Text
                            - columnName: translatedtext
                              prettyName: Translated Text
                            - columnName: entities.gpe
                              prettyName: Location
                            - columnName: topics
                              prettyName: Topics
                        labelOptions:
                            topics:
                                food: Food
                                water: Water
                                shelter: Shelter
                                med: Medicine
                                search: Search and Rescue
                                evac: Evacuation
                                infra: Infrastructure
                                utils: Utilities
                                crimeviolence: Crime / Violence
                                terrorism: Terrorism
                                regimechange: Regime Change
                        mappings:
                          date: createdAt
            lorelei_event-sf:
                prettyName: 'LORELEI Situation Frames'
                tables:
                    lorelei_event-sf:
                        prettyName: LORELEI Situation Frames
                        fields:
                            - columnName: id
                              prettyName: ID
                            - columnName: topic
                              prettyName: Topic
                            - columnName: location
                              prettyName: Location
                            - columnName: geoLocation.latitude
                              prettyName: Latitude
                            - columnName: geoLocation.longitude
                              prettyName: Longitude
                            - columnName: geoLocation.name
                              prettyName: Location Name
                            - columnName: frameid
                              prettyName: Frame ID
                        labelOptions:
                            topic:
                                food: Food
                                water: Water
                                shelter: Shelter
                                med: Medicine
                                search: Search and Rescue
                                evac: Evacuation
                                infra: Infrastructure
                                utils: Utilities
                                crimeviolence: Crime / Violence
                                terrorism: Terrorism
                                regimechange: Regime Change

dashboards:
    category: 'Select a task...'
    choices:
        lorelei:
            name: 'Situation Discovery'
            category: 'Select a datastore...'
            choices:
                lorelei:
                    name: THOR (Streaming)
                    layout: lorelei_event_layout
                    tables:
                        table_key_1: es1.lorelei_event.lorelei_event
                        table_key_2: es1.lorelei_event-sf.lorelei_event-sf
                    options:
                        connectOnLoad: true
                        customRequests:
                            - endpoint: ../data-pipeline
                              date: createdAt
                              id: id
                              notes:
                                  - "Please enter both a specific location (like a city name) and a specific emergency (like crime, food, medicine, rescue, shelter, terrorism, violence, or water)."
                                  - "Example:  I need medicine in Washington DC."
                              pretty: THOR Instant Messaging
                              properties:
                                - name: lang
                                  pretty: Language
                                  value: en
                                  choices:
                                      - value: en
                                        pretty: English
                                - name: originalText
                                  pretty: Original Text
                    fields:
                        original_text_key: es1.lorelei_event.lorelei_event.originaltext
                        translated_text_key: es1.lorelei_event.lorelei_event.translatedtext
                        date_field_key: es1.lorelei_event.lorelei_event.createdAt
                        id_field_key_1: es1.lorelei_event.lorelei_event.id
                        id_field_key_2: es1.lorelei_event-sf.lorelei_event-sf.id
                        latitude_key: es1.lorelei_event-sf.lorelei_event-sf.geoLocation.latitude
                        longitude_key: es1.lorelei_event-sf.lorelei_event-sf.geoLocation.longitude
                        group_field_key_topics: es1.lorelei_event-sf.lorelei_event-sf.topic
                        sf_location: es1.lorelei_event-sf.lorelei_event-sf.geoLocation.name
                        text_cloud_data_key_LOC: es1.lorelei_event.lorelei_event.entities.loc
                        text_cloud_data_key_PER: es1.lorelei_event.lorelei_event.entities.per
                        text_cloud_data_key_GPE: es1.lorelei_event.lorelei_event.geoLocations.name
                        text_cloud_data_key_ORG: es1.lorelei_event.lorelei_event.entities.org
                    relations:
                        - - es1.lorelei_event.lorelei_event.id
                          - es1.lorelei_event-sf.lorelei_event-sf.id
                        - - es1.lorelei_event.lorelei_event.topics
                          - es1.lorelei_event-sf.lorelei_event-sf.topic
                        - - es1.lorelei_event.lorelei_event.geoLocations.name
                          - es1.lorelei_event-sf.lorelei_event-sf.geoLocation.name
                        - - - es1.lorelei_event.lorelei_event.geoLocations.latitude
                            - es1.lorelei_event.lorelei_event.geoLocations.longitude
                          - - es1.lorelei_event-sf.lorelei_event-sf.geoLocation.latitude
                            - es1.lorelei_event-sf.lorelei_event-sf.geoLocation.longitude
                    contributors:
                        rpi:
                            orgName: 'Rensselaer Polytechnic Institute'
                            abbreviation: 'RPI'
                            contactName: 'Heng Ji'
                            contactEmail: 'jih@rpi.edu'
                            website: 'http://nlp.cs.rpi.edu/'
                            logo: 'RPI-logo.png'
                        isi:
                            orgName: 'University of Southern California, Information Sciences Institute'
                            abbreviation: 'USC/ISI'
                            contactName: 'Jonathan May'
                            contactEmail: 'jonmay@isi.edu'
                            website: 'https://www.isi.edu/'
                            logo: 'ISI-logo.png'

layouts:
    lorelei_event_layout:
        - name: News Feed
          type: newsFeed
          icon: newsFeed64
          col: 1
          row: 1
          sizex: 4
          sizey: 11
          bindings:
              title: Document Feed
              tableKey: table_key_1
              contentField: translated_text_key
              dateField: date_field_key
              idField: id_field_key_1
              secondaryContentField: original_text_key
              secondaryContentLabel: Original Text
              sortField: date_field_key
              titleContentField: translated_text_key
              ignoreSelf: false
              limit: 100
        - name: Map
          type: map
          icon: Map64
          col: 5
          row: 1
          sizex: 5
          sizey: 7
          bindings:
              title: Locations
              tableKey: table_key_2
              filterable: true
              name: EVENTS
              show: true
              type: cluster
              limit: 5000
              layers:
                  - title: Map
                    tableKey: table_key_2
                    latitudeField: latitude_key
                    longitudeField: longitude_key
                    dateField: date_field_key
                    colorField: group_field_key_topics
              mapType: leaflet
              west: 135
              north: -5
              east: 150
              south: -6
        - name: Text Cloud
          type: textCloud
          icon: TagCloud64
          col: 5
          row: 11
          sizex: 5
          sizey: 4
          selected: true
          bindings:
              title: Locations
              tableKey: table_key_1
              dataField: text_cloud_data_key_GPE
              preFilter: false
        - name: Data Table
          type: dataTable
          icon: ViewData64
          col: 10
          row: 1
          sizex: 3
          sizey: 6
          bindings:
            title: Situation Frames
            tableKey: table_key_2
            idField: id_field_key_2
            sortField: id_field_key_2
            limit: 100
            showFields:
                - sf_location
                - group_field_key_topics
            customColumnWidths:
                - - sf_location
                  - 160
                - - group_field_key_topics
                  - 80
            filterable: true
            singleFilter: true
            ignoreSelf: false
            filterFields:
                - id_field_key_2
        - name: Bar Chart
          type: aggregation
          icon: bar_chart
          col: 10
          row: 10
          sizex: 3
          sizey: 6
          bindings:
              title: Situation Types
              type: bar-h
              tableKey: table_key_2
              xField: group_field_key_topics
              limit: 11
              groupField: group_field_key_topics
              sortByAggregation: true
              ignoreSelf: true
              contributionKeys:
                - isi
