datastores:
    es_1:
        host: localhost
        type: elasticsearch
        databases:
            earthquakes:
                prettyName: Earthquakes Elasticsearch 6
                tables:
                    quakedata:
                        prettyName: Earthquake Data
                        fields:
                            - columnName: id
                              prettyName: ID
                            - columnName: depth
                              prettyName: Depth
                            - columnName: latitude
                              prettyName: Latitude
                            - columnName: longitude
                              prettyName: Longitude
                            - columnName: mag
                              prettyName: Magnitude
                            - columnName: magType
                              prettyName: Magnitude Type
                            - columnName: net
                              prettyName: Net
                            - columnName: time
                              prettyName: Time
                            - columnName: type
                              prettyName: Type
                            - columnName: _id
                              prettyName: ES ID

dashboards:
    name: Earthquakes Elasticsearch 6 Dashboard
    layout: earthquakes_layout
    options:
        connectOnLoad: true

layouts:
    earthquakes_layout:
        - type: aggregation
          col: 1
          row: 1
          sizex: 6
          sizey: 4
          bindings:
              title: Timeline
              type: histogram
              tableKey: es_1.earthquakes.quakedata
              xField: es_1.earthquakes.quakedata.time
              granularity: dayOfMonth
              groupField: es_1.earthquakes.quakedata.net
              ignoreSelf: true
              limit: 100

        - type: aggregation
          col: 1
          row: 5
          sizex: 6
          sizey: 4
          bindings:
              title: Networks
              type: bar-h
              tableKey: es_1.earthquakes.quakedata
              xField: es_1.earthquakes.quakedata.net
              groupField: es_1.earthquakes.quakedata.net
              sortByAggregation: true
              ignoreSelf: true
              limit: 11

        - type: aggregation
          col: 1
          row: 9
          sizex: 6
          sizey: 4
          bindings:
              title: Magnitudes
              type: histogram
              tableKey: es_1.earthquakes.quakedata
              xField: es_1.earthquakes.quakedata.mag
              groupField: es_1.earthquakes.quakedata.net
              ignoreSelf: true
              limit: 100

        - type: aggregation
          col: 1
          row: 13
          sizex: 6
          sizey: 4
          bindings:
              title: Depths
              type: histogram
              tableKey: es_1.earthquakes.quakedata
              xField: es_1.earthquakes.quakedata.depth
              groupField: es_1.earthquakes.quakedata.net
              ignoreSelf: true
              limit: 100

        - type: map
          col: 7
          row: 1
          sizex: 6
          sizey: 10
          bindings:
              title: Locations
              mapType: leaflet
              tableKey: es_1.earthquakes.quakedata
              limit: 5000
              layers:
                  - title: Earthquakes
                    tableKey: es_1.earthquakes.quakedata
                    latitudeField: es_1.earthquakes.quakedata.latitude
                    longitudeField: es_1.earthquakes.quakedata.longitude
                    colorField: es_1.earthquakes.quakedata.net

        - type: dataTable
          col: 7
          row: 11
          sizex: 6
          sizey: 6
          bindings:
              title: Raw Data
              tableKey: es_1.earthquakes.quakedata
              sortField: es_1.earthquakes.quakedata.time
              ignoreSelf: false
              limit: 100

