# config for demo with Humanity Roads at Nepal August 15-17 2018

datastores:
    es1:
        host: localhost
        type: elasticsearchrest
        databases:
            ll_nepal_08_14:
                prettyName: Nepal_08_14
                tables:
                    annotations:
                        prettyName: Annotations
                        fields:
                            - columnName: createdAt
                              prettyName: Date Created
                            - columnName: topic
                              prettyName: Need Type
                            - columnName: location
                              prettyName: Location
                            - columnName: status
                              prettyName: Status
                            - columnName: llAnnotation.Status
                              prettyName: Status
                            - columnName: translatedText
                              prettyName: Translated Text
                            - columnName: originalText
                              prettyName: Original Text
                        labelOptions:
                            topic:
                                food: Food
                                water: Water
                                shelter: Shelter
                                med: Medicine
                                search: Search and Rescue
                                evac: Evacuation
                                infra: Infrastructure
                                utils: Utilities
                                crimeviolence: Crime /  Violence
                                terrorism: Terrorism
                                regimechange: Regime Change
                        mappings:
                            date: createdAt
            ldc_uyg_jul_18:
                prettyName: Uyghur LDC, July 2018
                tables:
                    ui_out:
                        prettyName: UI out
                        fields:
                            - columnName: createdDate
                              prettyName: Date Created
                            - columnName: topic
                              prettyName: Need Type
                            - columnName: location
                              prettyName: Location
                            - columnName: status
                              prettyName: Status
                            - columnName: translatedText
                              prettyName: Translated Text
                            - columnName: originalText
                              prettyName: Original Text
                        labelOptions:
                            topic:
                                food: Food
                                water: Water
                                shelter: Shelter
                                med: Medicine
                                search: Search and Rescue
                                evac: Evacuation
                                infra: Infrastructure
                                utils: Utilities
                                crimeviolence: Crime /  Violence
                                terrorism: Terrorism
                                regimechange: Regime Change
                        mappings:
                            date: createDate

dashboards:
    category: 'Select a task...'
    choices:
        situation_discovery:
            name: 'Situation Discovery'
            category: 'Select a datastore...'
            choices:
                uyg_ldc_discovery:
                    name: Uyghur LDC
                    layout: uyghur-ldc-sd
                    tables:
                        table_key_1: es1.ldc_uyg_jul_18.ui_out
                    fields:
                        field_key_1: es1.ldc_uyg_jul_18.ui_out.originalText
                        field_key_2: es1.ldc_uyg_jul_18.ui_out.translatedText
                    options:
                        connectOnLoad: true
                        simpleFilter:
                            tableKey: table_key_1
                            fieldKey: field_key_2
                            placeHolder: Search
                    contributors:
                        org_1:
                            orgName: 'Some Organization 1'
                            abbreviation: 'ABC'
                            piTeamLead: 'PI/Team Lead Name'
                            contactInfo: 'Contact Information'
                            website: '<a href="">Company Website</a>'
                            logo: 'verdi-favicon'
                        org_2:
                            orgName: 'Some Organization 2'
                            abbreviation: 'XYZ'
                            piTeamLead: 'PI/Team Lead Name'
                            contactInfo: 'Contact Information'
                            website: '<a href="" target>Company Website</a>'
                            logo: 'verdi-favicon'
                nepal_elisa_discovery:
                    name: Nepal ELISA
                    layout: nepal-elisa-sd
                    tables:
                        table_key_1: es1.ll_nepal_08_14.annotations
                    fields:
                        field_key_1: es1.ll_nepal_08_14.annotations.originalText
                    options:
                        connectOnLoad: false
                        simpleFilter:
                            tableKey: table_key_1
                            fieldKey: field_key_1
                            placeHolder: Search

layouts:
    nepal-elisa-sd:
        - name: Map
          type: map
          icon: Map64
          col: 1
          row: 1
          sizex: 4
          sizey: 7
          bindings:
              title: Locations
              tableKey: table_key_1
              filterable: true
              name: EVENTS
              show: true
              type: cluster
              limit: 20000
              layers:
                  - title: Map
                    tableKey: table_key_1
                    latitudeField: geoLocation.lat
                    longitudeField: geoLocation.lon
                    dateField: createdDate
                    colorField: topic
              mapType: leaflet
          minPixelx: 320
          minPixely: 240
          minSizex: 3
          minSizey: 5
        - name: Timeline
          type: timeline
          icon: Timeline64
          col: 1
          row: 8
          sizex: 4
          sizey: 6
          bindings:
              title: Timeline
              tableKey: table_key_1
              dateField: createdAt
              granularity: hour
          minPixelx: 320
          minPixely: 240
          minSizex: 3
          minSizey: 3
        - name: Text Cloud
          type: textCloud
          icon: TagCloud64
          col: 5
          row: 1
          sizex: 3
          sizey: 5
          $$hashKey: object:35
          selected: true
          bindings:
              title: Locations
              tableKey: table_key_1
              dataField: location
              preFilter: false
          id: 431a862e-2b4d-4c4d-92c6-5c4c54515ea7
          minPixelx: 320
          minPixely: 240
          minSizex: 4
          minSizey: 3
        - name: Bar Chart
          type: aggregation
          icon: bar_chart
          col: 5
          row: 6
          sizex: 3
          sizey: 8
          bindings:
              title: Need Type
              type: bar-h
              tableKey: table_key_1
              xField: topic
              limit: 11
              groupField: topic
              sortByAggregation: true
          minPixelx: 320
          minPixely: 240
          minSizex: 3
          minSizey: 3
        - name: Data Table
          type: dataTable
          icon: ViewData64
          col: 8
          row: 1
          sizex: 5
          sizey: 7
          bindings:
              title: Tweet List
              tableKey: table_key_1
              idField: _id
              sortField: createdAt
              limit: 100
              allColumnStatus: hide
              exceptionsToStatus:
                  - createdAt
                  - translatedText
                  - mediaEntities.mediaURLHttps
              customColumnWidths:
                  - createdAt
                    55
                  - translatedText
                    182
                  - mediaEntities.mediaURLHttps
                    25
              filterable: false
              filterFields:
                  - _id
              singleFilter: true
              ignoreSelf: false
          minPixelx: 320
          minPixely: 240
          minSizex: 4
          minSizey: 3
        - name: Annotation Viewer
          type: annotationViewer
          icon: documentViewer64
          col: 8
          row: 8
          sizex: 2
          sizey: 6
          bindings:
              title: Selected Text
              tableKey: table_key_1
              linkField: translatedText
              idField: _id
              respondMode: true
          minPixelx: 320
          minPixely: 240
          minSizex: 2
          minSizey: 3
        - name: Media Viewer
          type: mediaViewer
          icon: mediaViewer
          col: 10
          row: 8
          sizex: 3
          sizey: 6
          bindings:
              title: Media Viewer
              tableKey: table_key_1
              id: _id
              idField: _id
              linkField: mediaEntities.mediaURLHttps
              resize: true
              maxHeight: 500
              maxWidth: 500
              typeMap:
                  bmp: img
                  jpg: img
                  jpeg: img
                  png: img
          minPixelx: 320
          minPixely: 240
          minSizex: 3
          minSizey: 4
    uyghur-ldc-sd:
        - name: Data Table
          type: dataTable
          icon: ViewData64
          col: 1
          row: 1
          sizex: 4
          sizey: 12
          bindings:
              title: Document Feed
              tableKey: table_key_1
              idField: _id
              sortField: createdDate
              limit: 100
              allColumnStatus: hide
              exceptionsToStatus:
                  - createdDate
                  - originalText
              customColumnWidths:
                  - createdDate
                    15
                  - originalText
                    220
              filterable: false
              filterFields:
                  - id
              singleFilter: true
              ignoreSelf: false
              checkDuplicateField: originalText
          minPixelx: 320
          minPixely: 240
          minSizex: 3
          minSizey: 3
        - name: Map
          type: map
          icon: Map64
          col: 5
          row: 1
          sizex: 4
          sizey: 7
          bindings:
              title: Locations
              tableKey: table_key_1
              filterable: true
              name: EVENTS
              show: true
              type: cluster
              limit: 5000
              layers:
                  - title: Map
                    tableKey: table_key_1
                    latitudeField: geoLocation.lat
                    longitudeField: geoLocation.lon
                    dateField: createdDate
                    colorField: topic
              mapType: leaflet
              west: 30.5
              north: 49
              east: 127
              south: 10.6
          minPixelx: 320
          minPixely: 240
          minSizex: 3
          minSizey: 5
        - name: Bar Chart
          type: aggregation
          icon: bar_chart
          col: 5
          row: 8
          sizex: 4
          sizey: 5
          bindings:
              title: Need Type
              type: bar-h
              tableKey: table_key_1
              xField: topic
              limit: 11
              groupField: topic
              sortByAggregation: true
          minPixelx: 320
          minPixely: 240
          minSizex: 2
          minSizey: 3
          contributorKeys:
            - org_1
            - org_2
        - name: Data Table
          type: dataTable
          icon: ViewData64
          col: 9
          row: 1
          sizex: 4
          sizey: 8
          bindings:
              title: Situation Frames
              tableKey: table_key_1
              sortField: createdDate
              idField: _id
              limit: 100
              allColumnStatus: hide
              exceptionsToStatus:
                  - createdDate
                  - topic
                  - location
                  - status
              customColumnWidths:
                  - createdDate
                    42
                  - topic
                    85
                  - location
                    85
                  - status
                    105
              filterable: false
              filterFields:
                  - _id
              singleFilter: true
              ignoreSelf: false
              checkDuplicateField: originalText
          minPixelx: 320
          minPixely: 240
          minSizex: 3
          minSizey: 3
        - name: Annotation Viewer
          type: annotationViewer
          icon: documentViewer64
          col: 9
          row: 9
          sizex: 2
          sizey: 4
          bindings:
              title: Original Text
              tableKey: table_key_1
              linkField: originalText
              idField: _id
              respondMode: true
          minPixelx: 320
          minPixely: 240
          minSizex: 2
          minSizey: 3
        - name: Annotation Viewer
          type: annotationViewer
          icon: documentViewer64
          col: 11
          row: 9
          sizex: 2
          sizey: 4
          bindings:
              title: Translated Text
              tableKey: table_key_1
              linkField: translatedText
              idField: _id
              respondMode: true
          minPixelx: 320
          minPixely: 240
          minSizex: 2
          minSizey: 3
        - name: Text Cloud
          type: textCloud
          icon: TagCloud64
          col: 5
          row: 13
          sizex: 3
          sizey: 4
          $$hashKey: object:35
          selected: true
          bindings:
              title: Locations
              tableKey: table_key_1
              dataField: location
              preFilter: false
          id: 431a862e-2b4d-4c4d-92c6-5c4c54515ea7
          minPixelx: 320
          minPixely: 240
          minSizex: 3
          minSizey: 4
