datasets:
  -
    name: Medifor User Workbench 05-18-18 (NC2017 Dev + Eval)
    datastore: elasticsearch
    hostname: localhost
    layout: User
    connectOnLoad: true
    databases:
      -
        name: output_051618
        prettyName: Scores
        tables:
          -
            name: doc
            prettyName: Item
            fields:
      -
        name: merged_051618
        prettyName: Inputs
        tables:
          -
            name: doc
            prettyName: Item
            fields:
    relations:
      -
        members:
          -
            database: output_051618
            table: doc
            field: FileID
          -
            database: merged_051618
            table: doc
            field: ProbeFileID

  -
    name: Developer Dashboard 05-18-18 (NC2017 Dev + Eval)
    datastore: elasticsearch
    hostname: localhost
    layout: Dev
    databases:
      -
        name: output_051618
        prettyName: Scores
        tables:
          -
            name: doc
            prettyName: Item
            fields:
      -
        name: merged_051618
        prettyName: Inputs
        tables:
          -
            name: doc
            prettyName: Item
            fields:
    relations:
      -
        members:
          -
            database: output_051618
            table: doc
            field: FileID
          -
            database: merged_051618
            table: doc
            field: ProbeFileID

layouts:
  User:
    -
      col: 1
      row: 1
      sizex: 8
      sizey: 12
      type: thumbnailGrid
      bindings:
        title: Probe Gallery
        limit: 25
        database: merged_051618
        table: doc
        ascending: true
        border: grey
        cropAndScale:
        filterField: ProbeFileID
        idField: _id
        linkField: ProbeDir
        linkPrefix: http://10.107.5.173:8000
        nameField: ProbeFileID
        objectIdField:
        objectNameField: ManipulationString
        openOnMouseClick: false
        percentField: ManipulationPercentage
        predictedNameField:
        sortField: ProbeFileID
        styleClass: style2
        textMap:
            actual: 'Truth'
            percentage: 'Score'
            prediction: ''
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq:
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid

    -
      col: 9
      row: 1
      sizex: 8
      sizey: 6
      type: barChart
      bindings:
        title: Manipulations
        limit: 100
        database: merged_051618
        table: doc
        dataField: Manipulations
        aggregation: count
        andFilters: false
        chartType: horizontalBar
        yPercentage: 0.3
    -
      col: 9
      row: 7
      sizex: 8
      sizey: 6
      type: barChart
      bindings:
        title: Indicators
        limit: 100
        database: output_051618
        table: doc
        dataField: AnalyticName
        aggregation: average
        aggregationField: IndicatorScore
        andFilters: false
        chartType: horizontalBar
        scaleManually: true
        scaleMin: 0
        scaleMax: 1
        yPercentage: 0.3

    -
      col: 17
      row: 1
      sizex: 8
      sizey: 6
      type: mediaViewer
      bindings:
        title: Probe
        database: merged_051618
        table: doc
        border: grey
        idField: _id
        linkField: ProbeDir
        linkPrefix: http://10.107.5.173:8000
        nameField: ProbeFileID
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq:
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid
    -
      col: 17
      row: 7
      sizex: 8
      sizey: 6
      type: mediaViewer
      bindings:
        title: Integrity Mask
        database: merged_051618
        table: doc
        border: grey
        idField: _id
        linkField: MasksDir
        linkPrefix: http://10.107.5.173:8000
        nameField: ProbeFileID
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq:
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid

    -
      col: 9
      row: 13
      sizex: 8
      sizey: 4
      type: documentViewer
      bindings:
        title: Metadata
        limit: 100
        database: merged_051618
        table: doc
        dataField: ProbeFileID
        idField: _id
        showSelect: true
        metadataFields:
          -
            name: Media
            field: ProbeFileID
          -
            name: File Type
            field: FileType
          -
            name: Camera
            field: CameraID
          -
            name: Height
            field: ProbeHeight
          -
            name: Width
            field: ProbeWidth

    -
      col: 1
      row: 13
      sizex: 8
      sizey: 4
      type: filterBuilder
    -
      col: 17
      row: 13
      sizex: 8
      sizey: 4
      type: thumbnailGrid
      bindings:
        title: Contributors
        limit: 25
        database: merged_051618
        table: doc
        ascending: true
        border: grey
        cropAndScale:
        filterField: BaseBrowserFileName
        idField: _id
        linkField: WorldDir
        linkPrefix: http://10.107.5.173:8000
        nameField: BaseBrowserFileName
        objectIdField:
        objectNameField:
        openOnMouseClick: false
        percentField:
        predictedNameField:
        sortField: BaseBrowserFileName
        styleClass: style2
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq:
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid

  Dev:
    -
      col: 1
      row: 1
      sizex: 8
      sizey: 12
      type: thumbnailGrid
      bindings:
        title: Probe Gallery
        limit: 25
        database: merged_051618
        table: doc
        ascending: true
        border: grey
        cropAndScale:
        filterField: ProbeFileID
        idField: _id
        linkField: ProbeDir
        linkPrefix: http://10.107.5.173:8000
        nameField: ProbeFileID
        objectIdField:
        objectNameField: ManipulationString
        openOnMouseClick: false
        percentField: ManipulationPercentage
        predictedNameField:
        sortField: ProbeFileID
        styleClass: style2
        textMap:
            actual: 'Truth'
            percentage: 'Score'
            prediction: ''
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq:
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid

    -
      col: 9
      row: 1
      sizex: 8
      sizey: 6
      type: barChart
      bindings:
        title: Manipulations
        limit: 100
        database: merged_051618
        table: doc
        dataField: Manipulations
        aggregation: count
        andFilters: false
        chartType: horizontalBar
        yPercentage: 0.3
    -
      col: 9
      row: 7
      sizex: 8
      sizey: 6
      type: barChart
      bindings:
        title: Indicators
        limit: 100
        database: output_051618
        table: doc
        dataField: AnalyticName
        aggregation: average
        aggregationField: IndicatorScore
        andFilters: false
        chartType: horizontalBar
        scaleManually: true
        scaleMin: 0
        scaleMax: 1
        yPercentage: 0.3

    -
      col: 17
      row: 1
      sizex: 8
      sizey: 6
      type: mediaViewer
      bindings:
        title: Probe
        database: merged_051618
        table: doc
        border: grey
        idField: _id
        linkField: ProbeDir
        linkPrefix: http://10.107.5.173:8000
        nameField: ProbeFileID
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq:
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid
    -
      col: 17
      row: 7
      sizex: 8
      sizey: 6
      type: mediaViewer
      bindings:
        title: Integrity Mask
        database: merged_051618
        table: doc
        border: grey
        idField: _id
        linkField: MasksDir
        linkPrefix: http://10.107.5.173:8000
        nameField: ProbeFileID
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq:
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid

    -
      col: 9
      row: 13
      sizex: 8
      sizey: 4
      type: documentViewer
      bindings:
        title: Metadata
        limit: 100
        database: merged_051618
        table: doc
        dataField: ProbeFileID
        idField: _id
        showSelect: true
        metadataFields:
          -
            name: Media
            field: ProbeFileID
          -
            name: File Type
            field: FileType
          -
            name: Camera
            field: CameraID
          -
            name: Height
            field: ProbeHeight
          -
            name: Width
            field: ProbeWidth

    -
      col: 1
      row: 13
      sizex: 8
      sizey: 4
      type: filterBuilder
    -
      col: 17
      row: 13
      sizex: 8
      sizey: 4
      type: thumbnailGrid
      bindings:
        title: Contributors
        limit: 25
        database: merged_051618
        table: doc
        ascending: true
        border: grey
        cropAndScale:
        filterField: BaseBrowserFileName
        idField: _id
        linkField: WorldDir
        linkPrefix: http://10.107.5.173:8000
        nameField: BaseBrowserFileName
        objectIdField:
        objectNameField:
        openOnMouseClick: false
        percentField:
        predictedNameField:
        sortField: BaseBrowserFileName
        styleClass: style2
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq:
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid

    -
      col: 1
      row: 17
      sizex: 8
      sizey: 4
      type: textCloud
      bindings:
        title: Input Runs
        limit: 100
        database: merged_051618
        table: doc
        dataField: DataName
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true
    -
      col: 9
      row: 17
      sizex: 8
      sizey: 4
      type: textCloud
      bindings:
        title: Input Tasks
        limit: 100
        database: merged_051618
        table: doc
        dataField: TaskID
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true
    -
      col: 17
      row: 17
      sizex: 8
      sizey: 4
      type: mediaViewer
      bindings:
        title: Contributor (World)
        database: merged_051618
        table: doc
        border: grey
        idField: _id
        linkField: WorldDir
        linkPrefix: http://10.107.5.173:8000
        nameField: BaseBrowserFileName
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq:
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid

    -
      col: 1
      row: 21
      sizex: 8
      sizey: 4
      type: textCloud
      bindings:
        title: File Types
        limit: 100
        database: merged_051618
        table: doc
        dataField: FileType
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true
    -
      col: 9
      row: 21
      sizex: 8
      sizey: 4
      type: textCloud
      bindings:
        title: Is Manipulated?
        database: merged_051618
        table: doc
        dataField: IsTarget
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true
    -
      col: 17
      row: 21
      sizex: 8
      sizey: 4
      type: textCloud
      bindings:
        title: Manipulations
        limit: 100
        database: merged_051618
        table: doc
        dataField: Manipulations
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true

    -
      col: 1
      row: 25
      sizex: 8
      sizey: 4
      type: textCloud
      bindings:
        title: Output Runs
        limit: 100
        database: output_051618
        table: doc
        dataField: DataName
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true
    -
      col: 9
      row: 25
      sizex: 8
      sizey: 4
      type: textCloud
      bindings:
        title: Analytics
        limit: 100
        database: output_051618
        table: doc
        dataField: AnalyticName
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true
    -
      col: 17
      row: 25
      sizex: 8
      sizey: 4
      type: textCloud
      bindings:
        title: Output Status
        limit: 100
        database: output_051618
        table: doc
        dataField: OutputStatus
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true

    -
      col: 1
      row: 29
      sizex: 8
      sizey: 4
      type: dataTable
      bindings:
        title: Merged Index & Ref Data
        database: merged_051618
        table: doc
        idField: _id
        sortField: ProbeFileID
        filterable: true
        ignoreSelf: true
        singleFilter: true
        skinny: true
        sortDescending: false
        allColumnStatus: hide
        fieldsConfig:
          -
            name: ProbeFileName
          -
            name: DataName
          -
            name: TaskID
          -
            name: IsTarget
          -
            name: Manipulations
        filterFields:
          -
            ProbeFileID
    -
      col: 9
      row: 29
      sizex: 8
      sizey: 4
      type: dataTable
      bindings:
        title: Output Data
        database: output_051618
        table: doc
        idField: _id
        sortField: FileID
        filterable: true
        singleFilter: true
        skinny: true
        sortDescending: false
        allColumnStatus: hide
        fieldsConfig:
          -
            name: DataName
          -
            name: AnalyticName
          -
            name: FileID
          -
            name: IndicatorScore
          -
            name: OutputStatus
        filterFields:
          -
            FileID
    -
      col: 17
      row: 29
      sizex: 8
      sizey: 4
      type: mediaViewer
      bindings:
        title: Output Mask
        database: output_051618
        table: doc
        border: grey
        idField: _id
        linkField: mask
        linkPrefix: http://10.107.5.173:8000
        nameField: FileID
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq:
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid

    -
      col: 1
      row: 33
      sizex: 24
      sizey: 4
      type: barChart
      bindings:
        title: Number of Images per Rounded Indicator Score
        limit: 500
        database: output_051618
        table: doc
        dataField: rounded
        sortAlphabetically: true
