datasets:
  -
    name: Medifor User Workbench 05-16-18 (NC2017 Dev)
    datastore: elasticsearch
    hostname: localhost
    layout: User
    connectOnLoad: true
    databases:
      -
        name: nc2017_output_051018
        prettyName: Scores
        tables:
          -
            name: doc
            prettyName: Item
            fields:
      -
        name: nc2017_merged_051018
        prettyName: Inputs
        tables:
          -
            name: doc
            prettyName: Item
            fields:
    relations:
      -
        members:
          -
            database: nc2017_output_051018
            table: doc
            field: image
          -
            database: nc2017_merged_051018
            table: doc
            field: ProbeBrowserFileName

  -
    name: Developer Dashboard 05-08-18 (NC2017 Dev)
    datastore: elasticsearch
    hostname: localhost
    layout: NC2017
    databases:
      -
        name: nc2017_output_051018
        prettyName: Scores
        tables:
          -
            name: doc
            prettyName: Item
            fields:
      -
        name: nc2017_merged_051018
        prettyName: Inputs
        tables:
          -
            name: doc
            prettyName: Item
            fields:
    relations:
      -
        members:
          -
            database: nc2017_output_051018
            table: doc
            field: image
          -
            database: nc2017_merged_051018
            table: doc
            field: ProbeBrowserFileName

layouts:
  NC2017:
    -
      col: 1
      row: 1
      sizex: 8
      sizey: 6
      type: dataTable
      bindings:
        title: Input Media
        database: nc2017_merged_051018
        table: doc
        idField: _id
        sortField: ProbeBrowserFileName
        filterable: true
        ignoreSelf: true
        singleFilter: true
        skinny: true
        sortDescending: false
        allColumnStatus: hide
        fieldsConfig:
          -
            name: ProbeBrowserFileName
        filterFields:
          -
            ProbeBrowserFileName
    -
      col: 9
      row: 1
      sizex: 8
      sizey: 6
      type: mediaViewer
      bindings:
        title: Image / Video
        database: nc2017_merged_051018
        table: doc
        border: grey
        idField: _id
        linkField: Source
        linkPrefix: http://10.107.5.173:8000
        nameField: ProbeBrowserFileName
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq: img
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid
    -
      col: 17
      row: 1
      sizex: 8
      sizey: 6
      type: mediaViewer
      bindings:
        title: Mask
        database: nc2017_merged_051018
        table: doc
        border: grey
        idField: _id
        linkField: MaskSource
        linkPrefix: http://10.107.5.173:8000
        nameField: ProbeBrowserFileName
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq: img
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid

    -
      col: 1
      row: 7
      sizex: 8
      sizey: 6
      type: dataTable
      bindings:
        title: Output Data
        database: nc2017_output_051018
        table: doc
        idField: _id
        sortField: image
        filterable: true
        singleFilter: true
        skinny: true
        sortDescending: false
        allColumnStatus: hide
        fieldsConfig:
          -
            name: analytic
          -
            name: image
          -
            name: score
        filterFields:
          -
            image
    -
      col: 9
      row: 7
      sizex: 8
      sizey: 6
      type: mediaViewer
      bindings:
        title: Output Mask
        database: nc2017_output_051018
        table: doc
        border: grey
        idField: _id
        linkField: mask
        linkPrefix: http://10.107.5.173:8000
        nameField: image
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq: img
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid
    -
      col: 17
      row: 7
      sizex: 8
      sizey: 10
      type: barChart
      bindings:
        title: Output (AVG) per Analytic
        database: nc2017_output_051018
        table: doc
        dataField: analytic
        aggregation: average
        aggregationField: score
        andFilters: false
        chartType: horizontalBar
        scaleManually: true
        scaleMin: -1
        scaleMax: 1
        limit: 100
    -
      col: 1
      row: 13
      sizex: 16
      sizey: 4
      type: barChart
      bindings:
        title: Number of Images per Rounded Indicator Score
        database: nc2017_output_051018
        table: doc
        dataField: rounded
        sortAlphabetically: true
        limit: 500

    -
      col: 1
      row: 17
      sizex: 6
      sizey: 3
      type: textCloud
      bindings:
        title: Cameras
        database: nc2017_merged_051018
        table: doc
        dataField: CameraID
        limit: 100
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true
    -
      col: 1
      row: 20
      sizex: 6
      sizey: 3
      type: textCloud
      bindings:
        title: File Types
        database: nc2017_merged_051018
        table: doc
        dataField: Type
        limit: 100
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true
    -
      col: 7
      row: 17
      sizex: 6
      sizey: 6
      type: textCloud
      bindings:
        title: Analytics
        database: nc2017_output_051018
        table: doc
        dataField: analytic
        limit: 100
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true
    -
      col: 13
      row: 17
      sizex: 6
      sizey: 3
      type: textCloud
      bindings:
        title: Runs
        database: nc2017_output_051018
        table: doc
        dataField: run
        limit: 100
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true
    -
      col: 13
      row: 20
      sizex: 6
      sizey: 3
      type: textCloud
      bindings:
        title: Is Manipulated?
        database: nc2017_merged_051018
        table: doc
        dataField: IsTarget
        andFilters: false
        ignoreSelf: true
        showCounts: true
    -
      col: 19
      row: 17
      sizex: 6
      sizey: 6
      type: textCloud
      bindings:
        title: Manipulations
        database: nc2017_merged_051018
        table: doc
        dataField: Manipulations
        limit: 100
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true

    -
      col: 1
      row: 23
      sizex: 12
      sizey: 4
      type: filterBuilder
    -
      col: 13
      row: 23
      sizex: 6
      sizey: 4
      type: textCloud
      bindings:
        title: Tasks
        database: nc2017_merged_051018
        table: doc
        dataField: TaskID
        limit: 100
        andFilters: false
        ignoreSelf: true
        paragraphs: true
        showCounts: true
    -
      col: 19
      row: 23
      sizex: 6
      sizey: 8
      type: documentViewer
      bindings:
        title: Test
        database: nc2017_merged_051018
        table: doc
        dataField: ProbeBrowserFileName
        idField: _id
        limit: 100
        showSelect: true
        metadataFields:
          -
            name: Media
            field: ProbeBrowserFileName
        popoutFields:
          -
            name: Media File
            field: ProbeBrowserFileName
          -
            name: Task
            field: TaskID
          -
            name: Type
            field: Type
          -
            name: Camera
            field: CameraID
          -
            name: Height
            field: ProbeHeight
          -
            name: Width
            field: ProbeWidth
          -
            name: Is Manipulated?
            field: IsTarget
          -
            name: Manipulations
            field: Manipulations
          -
            name: Mask
            field: ProbeMaskFileName

  User:
    -
      col: 1
      row: 1
      sizex: 8
      sizey: 12
      type: thumbnailGrid
      bindings:
        title: Probe Gallery
        database: nc2017_merged_051018
        table: doc
        ascending: true
        border: grey
        cropAndScale:
        filterField: ProbeBrowserFileName
        idField: _id
        linkField: Source
        linkPrefix: http://10.107.5.173:8000
        nameField: ProbeBrowserFileName
        objectIdField:
        objectNameField: IsTarget
        openOnMouseClick: false
        percentField:
        predictedNameField:
        sortField: ProbeBrowserFileName
        styleClass: style2
        textMap:
            actual: 'Truth'
            percentage: 'Score'
            prediction: ''
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq: img
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid

    -
      col: 9
      row: 1
      sizex: 8
      sizey: 6
      type: barChart
      bindings:
        title: Manipulations
        database: nc2017_merged_051018
        table: doc
        dataField: Manipulations
        aggregation: count
        andFilters: false
        chartType: horizontalBar
        limit: 100
        yPercentage: 0.3
    -
      col: 9
      row: 7
      sizex: 8
      sizey: 6
      type: barChart
      bindings:
        title: Indicators
        database: nc2017_output_051018
        table: doc
        dataField: analytic
        aggregation: average
        aggregationField: score
        andFilters: false
        chartType: horizontalBar
        scaleManually: true
        scaleMin: -1
        scaleMax: 1
        limit: 100
        yPercentage: 0.3

    -
      col: 17
      row: 1
      sizex: 8
      sizey: 6
      type: mediaViewer
      bindings:
        title: Probe
        database: nc2017_merged_051018
        table: doc
        border: grey
        idField: _id
        linkField: Source
        linkPrefix: http://10.107.5.173:8000
        nameField: ProbeBrowserFileName
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq: img
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid
    -
      col: 17
      row: 7
      sizex: 8
      sizey: 6
      type: mediaViewer
      bindings:
        title: Integrity Mask
        database: nc2017_merged_051018
        table: doc
        border: grey
        idField: _id
        linkField: MaskSource
        linkPrefix: http://10.107.5.173:8000
        nameField: ProbeBrowserFileName
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq: img
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid

    -
      col: 9
      row: 13
      sizex: 8
      sizey: 4
      type: documentViewer
      bindings:
        title: Metadata
        database: nc2017_merged_051018
        table: doc
        dataField: ProbeBrowserFileName
        idField: _id
        limit: 100
        showSelect: true
        metadataFields:
          -
            name: Media
            field: ProbeFileID
          -
            name: File Type
            field: Type
          -
            name: Camera
            field: CameraID
          -
            name: Height
            field: ProbeHeight
          -
            name: Width
            field: ProbeWidth

    -
      col: 1
      row: 13
      sizex: 8
      sizey: 4
      type: filterBuilder
    -
      col: 17
      row: 13
      sizex: 8
      sizey: 4
      type: thumbnailGrid
      bindings:
        title: Contributors
        database: nc2017_merged_051018
        table: doc
        ascending: true
        border: grey
        cropAndScale:
        filterField: BaseBrowserFileName
        idField: _id
        linkField: BaseSource
        linkPrefix: http://10.107.5.173:8000
        nameField: BaseBrowserFileName
        objectIdField:
        objectNameField:
        openOnMouseClick: false
        percentField:
        predictedNameField:
        sortField: BaseBrowserFileName
        styleClass: style2
        typeMap:
            arw:
            bmp: img
            cr2:
            iiq: img
            jpg: img
            jpeg: img
            nef:
            png: img
            tif:
            avi: vid
            mp4: vid

